### ISSUE TITLE
actual_brightness changes to max upon launching certain applications

### ISSUE THREAD

**Issue by dougmercer** [guillaumezin/nvidiabl#104]
# Version Info
Linux Mint 17, Cinnamon
nvidia-331
nvidiabl installed using nvidiabl-dkms_0.87_all.deb
Laptop Make/Model: Lenovo y500
Video card configuration: (2) Nvidia 650M

# Issue 
When launching certain applications, (e.g., Firefox, Thunderbird) actual_brightness is modified from its current value to the max brightness (in my case, 127). 

If you'd like me to gather any specific info, I'd be happy to do so.

Thank you for all of your work in developing nvidiabl. This driver makes my laptop usable.

**Comment by tapir** [comment]
Same thing here.

I'm on Arch 64-bit with latest packages and nvidiabl compiled from AUR.
Brightness maxes out when one of these windows are focused: steam, firefox, popcorntime, cheese...

**Comment by dougmercer** [comment]
Turning off hardware acceleration for the affected apps resolved this issue.
