### ISSUE TITLE
Brightness is reset to maximum without notice

### ISSUE THREAD

**Issue by jroimartin** [guillaumezin/nvidiabl#32]
Hello,

The brightness is reset to the maximum value without notice. I've seen this behavior, for instance, when you set the brightness from a tty and then execute "startx", when you get into Xorg "cat /sys/class/backlight/nvidia_backlight/brightness" reports the last value (e.g. 42) but the screen is working with maximum brightness. In fact, if you exec "nvidia_backlight_down.sh" once, the value is updated to "117", which confirms that the last real value was "127".

Thanks in advance and keep up the good work!

Some **info** about my system:

**$ dmesg | grep nvidiabl**
[    6.505167] nvidiabl: loading driver version 0.73
[    6.505198] nvidiabl: Supported Nvidia graphics adapter 10de:06e9:103c:1505 detected
[    6.505374] nvidiabl: backup register value 0x400
[    6.505379] nvidiabl: autodetecting maximum
[    6.505383] nvidiabl: using value 0x400 as maximum
[    6.505387] nvidiabl: autodetecting off
[    6.505391] nvidiabl: using value 0x0 as off
[    6.505395] nvidiabl: autodetecting minimum
[    6.505399] nvidiabl: minimum is 5% of maximum
[    6.505403] nvidiabl: using value 0x64 as minimum

**$ lspci | grep VGA**
01:00.0 VGA compatible controller: NVIDIA Corporation G98 [GeForce 9300M GS](rev a1)

**$ uname -a**
Linux wopr 3.3.2-1-ARCH #1 SMP PREEMPT Sat Apr 14 09:48:37 CEST 2012 x86_64 Intel(R) Core(TM)2 Duo CPU T5800 @ 2.00GHz GenuineIntel GNU/Linux

**$ Xorg -version**
X.Org X Server 1.12.1
Release Date: 2012-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.3.1-1-ARCH x86_64 
Current Operating System: Linux wopr 3.3.2-1-ARCH #1 SMP PREEMPT Sat Apr 14 09:48:37 CEST 2012 x86_64
Kernel command line: root=/dev/sda5 resume=/dev/sda6 vga=792 acpi_backlight=vendor ro
Build Date: 14 April 2012  07:09:45AM

Current version of pixman: 0.24.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.

**$ cat /boot/grub/menu.lst**
...
kernel /boot/vmlinuz-linux root=/dev/sda5 resume=/dev/sda6 vga=792 acpi_backlight=vendor ro
...

**Laptop Model:** HP Pavilion dv3540es

**Comment by tapir** [comment]
@jroimartin since you closed this I'm assuming you have found a solution? Would you care to share? I'm having the exact same problem.

Thanks
